# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('batch_number', models.CharField(max_length=200)),
                ('sampling_time', models.DateTimeField()),
                ('lab_test_number', models.CharField(max_length=200, null=True)),
                ('sample_receiving_time', models.DateTimeField()),
                ('sample_source', models.CharField(max_length=200)),
                ('tank_number', models.CharField(max_length=200)),
                ('batch_quantity', models.CharField(max_length=200)),
                ('formulation_number', models.CharField(max_length=200)),
                ('sample_type', models.CharField(max_length=200)),
                ('comments', models.TextField(null=True)),
                ('releasing_time', models.DateTimeField()),
                ('permission_status', models.CharField(choices=[('Pen', 'Pending'), ('Apr', 'Approved'), ('Rej', 'Rejected'), ('Ver', 'Verified')], default='Pen', max_length=3)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductName')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=400)),
                ('sample_number', models.CharField(max_length=400)),
                ('test_type', models.CharField(max_length=400)),
                ('serial_number', models.CharField(max_length=400)),
                ('tank_number', models.CharField(max_length=400)),
                ('batch_size', models.CharField(max_length=400)),
                ('date_tested', models.DateTimeField()),
                ('time_in_date', models.DateTimeField()),
                ('time_out_date', models.DateTimeField()),
                ('blending_date', models.DateTimeField()),
                ('permission_status', models.CharField(choices=[('Pen', 'Pending'), ('Apr', 'Approved'), ('Rej', 'Rejected'), ('Ver', 'Verified')], default='Pen', max_length=3)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductName')),
            ],
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('mins', models.CharField(max_length=200)),
                ('maxs', models.CharField(max_length=200)),
                ('typical', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lir.ProductInfo')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductName')),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.TestName')),
            ],
        ),
    ]
