# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lir',
            name='ref_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
