# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lir', '0004_auto_20161023_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
