# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lir', '0005_auto_20161024_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='initial',
            field=models.BooleanField(default=False),
        ),
    ]
