# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lir', '0006_productinfo_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseCertificateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=400, null=True)),
                ('sample_source', models.CharField(max_length=400, null=True)),
                ('batch_number', models.CharField(max_length=400, null=True)),
                ('sampling_time', models.DateTimeField(null=True)),
                ('sample_tested', models.CharField(max_length=400, null=True)),
                ('filling_weight_calculations', models.CharField(max_length=400, null=True)),
                ('head_of_qa', models.CharField(max_length=400, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
