# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lir', '0007_releasecertificateinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequestform',
            name='batch_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
