# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lir', '0008_auto_20161029_1120'),
        ('lir', '0008_auto_20161029_1126'),
    ]

    operations = [
    ]
