# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_equipmentdetails_equipment_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementalAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAPReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('customer_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.CustomerContact')),
                ('equipment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.EquipmentDetails')),
            ],
        ),
        migrations.CreateModel(
            name='OilAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('oap_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oap.OAPReport')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressiveAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sampled', models.DateTimeField()),
                ('date_received', models.DateTimeField()),
                ('lab_number', models.CharField(max_length=200)),
                ('oil_life', models.CharField(max_length=200)),
                ('component_life', models.CharField(max_length=200)),
                ('filter_life', models.CharField(max_length=200)),
                ('daily_top_up', models.CharField(max_length=200)),
                ('oil_changed', models.CharField(max_length=100)),
                ('date_of_oil_renewed', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='oapreport',
            name='progressive_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oap.ProgressiveAnalysis'),
        ),
        migrations.AddField(
            model_name='elementalanalysis',
            name='oap_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oap.OAPReport'),
        ),
    ]
