# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oapreport',
            name='permission_status',
            field=models.CharField(choices=[('Pen', 'Pending'), ('Apr', 'Approved'), ('Rej', 'Rejected'), ('Ver', 'Verified')], default='Pen', max_length=3),
        ),
        migrations.AddField(
            model_name='progressiveanalysis',
            name='coolant_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progressiveanalysis',
            name='coolant_out',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progressiveanalysis',
            name='date_reported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressiveanalysis',
            name='oil_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progressiveanalysis',
            name='oil_out',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progressiveanalysis',
            name='reservior_temperature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progressiveanalysis',
            name='sump_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='component_life',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='daily_top_up',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='date_sampled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='filter_life',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='oil_changed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='oil_life',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
