# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oap', '0002_auto_20161106_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementalanalysis',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oilanalysis',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='date_of_oil_renewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressiveanalysis',
            name='lab_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
