# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oap', '0003_auto_20161107_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressiveanalysis',
            old_name='reservior_temperature',
            new_name='reservoir_temperature',
        ),
    ]
