# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oap', '0004_auto_20161107_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='oapreport',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oapreport',
            name='permission_status',
            field=models.CharField(choices=[('Ini', 'Initial'), ('Pen', 'Pending'), ('Apr', 'Approved'), ('Rej', 'Rejected'), ('Ver', 'Verified')], default='Ini', max_length=3),
        ),
    ]
