# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productname',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
