# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20161021_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttestdata',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producttestdata',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='testname',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testname',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
