# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20161024_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=400)),
                ('customer_contacts_name', models.CharField(max_length=200)),
                ('customer_contact', models.CharField(max_length=100)),
                ('reference_contact_name', models.CharField(max_length=200)),
                ('reference_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_number', models.CharField(max_length=200)),
                ('equipment_model', models.CharField(max_length=200)),
                ('component', models.CharField(max_length=400)),
                ('component_make', models.CharField(max_length=400)),
                ('component_model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('lube_oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductName')),
            ],
        ),
    ]
