# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_test_name', models.CharField(max_length=100)),
                ('scheduled_at', models.DateField()),
                ('next_schedule', models.DateField()),
                ('gross_day', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'Complete'), ('IC', 'Incomplete')], default='C', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_status', models.CharField(choices=[('Pen', 'Pending'), ('Apr', 'Approved'), ('Rej', 'Rejected'), ('Ver', 'Verified')], default='Pen', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibration_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.CalibrationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('I', 'Instrument'), ('E', 'Equipment'), ('MD', 'Measuring Device')], default='I', max_length=2)),
                ('model_number', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('IA', 'Inactive')], default='IA', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='calibrationreport',
            name='instrument_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.InstrumentInfo'),
        ),
        migrations.AddField(
            model_name='calibrationinfo',
            name='instrument_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.InstrumentInfo'),
        ),
    ]
