# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentinfo',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentinfo',
            name='instrument_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrumentinfo',
            name='instrument_name',
            field=models.CharField(default='instrument1', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentinfo',
            name='po_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentinfo',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentinfo',
            name='uploaded_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/instruments/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='instrumentinfo',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentinfo',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentinfo',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
