# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0002_auto_20161130_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationinfo',
            name='next_schedule',
        ),
        migrations.AddField(
            model_name='calibrationinfo',
            name='interval',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibrationinfo',
            name='occurred_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationinfo',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('IC', 'Incomplete')], default='IC', max_length=2),
        ),
    ]
