# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0003_auto_20161201_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_test_name', models.CharField(max_length=100)),
                ('scheduled_at', models.DateField()),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('gross_day', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'Complete'), ('IC', 'Incomplete')], default='IC', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='calibrationinfo',
            name='occurred_at',
        ),
        migrations.RemoveField(
            model_name='calibrationinfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='calibrationreport',
            name='calibration_info',
        ),
        migrations.RemoveField(
            model_name='calibrationreport',
            name='instrument_info',
        ),
        migrations.RemoveField(
            model_name='calibrationreport',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='calibrationreport',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('C', 'Complete')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='calibrationreport',
            name='permission_status',
            field=models.CharField(choices=[('Pen', 'Pending'), ('Apr', 'Approved'), ('Rej', 'Rejected')], default='Pen', max_length=3),
        ),
        migrations.AddField(
            model_name='calibrationtests',
            name='calibration_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.CalibrationReport'),
        ),
        migrations.AddField(
            model_name='calibrationtests',
            name='instrument_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.InstrumentInfo'),
        ),
    ]
