# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0004_auto_20161202_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationinfo',
            name='calibration_test_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
