# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0005_auto_20161203_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='documents/calibration/internal/%Y/%m/%d')),
                ('calibration_tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.CalibrationTests')),
            ],
        ),
    ]
