# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0007_calibrationtests_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationtests',
            name='scheduled_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
