# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0008_auto_20161218_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
