# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0009_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyCalibrationTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.CalibrationTests')),
            ],
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
